import { Distributor, Order } from "../types/orderType"

// Mock distributors data
export const mockDistributors: Distributor[] = [
  {
    _id: "dist-001",
    name: "FastTrack Logistics",
    email: "contact@fasttrack.com",
    phone: "+1-555-1001",
    address: "123 Logistics Ave",
    city: "New York",
    state: "NY",
    capacity: 100,
    currentOrders: 45,
    rating: 4.8,
    status: "active",
  },
  {
    _id: "dist-002",
    name: "QuickShip Express",
    email: "info@quickship.com",
    phone: "+1-555-1002",
    address: "456 Express Blvd",
    city: "Los Angeles",
    state: "CA",
    capacity: 150,
    currentOrders: 78,
    rating: 4.6,
    status: "active",
  },
  {
    _id: "dist-003",
    name: "Reliable Delivery Co",
    email: "support@reliable.com",
    phone: "+1-555-1003",
    address: "789 Delivery St",
    city: "Chicago",
    state: "IL",
    capacity: 80,
    currentOrders: 32,
    rating: 4.9,
    status: "active",
  },
]

// Mock data for demonstration
export const mockOrders: Order[] = [
  {
    _id: "1",
    orderNumber: "ORD-2024-001",
    customerId: "cust-001",
    customerEmail: "john.doe@example.com",
    customerName: "John Doe",
    items: [
      {
        product: {
          _id: "prod-001",
          name: "Classic Cotton T-Shirt",
          description: "Premium cotton t-shirt with modern fit",
          category: "Clothing",
          subcategory: "T-Shirts",
          fabric: "Cotton",
          occasion: "Casual",
          patternAndPrint: "Solid",
          style: "Classic",
          dateAdded: "2024-01-15T00:00:00Z",
          options: { fit: "Regular", neck: "Round" },
        },
        variant: {
          _id: "var-001",
          color: "Navy Blue",
          thumbnail: "/placeholder.svg?height=100&width=100",
          sizes: [
            { size: "M", marketPrice: 29.99, sellingPrice: 24.99, stock: 50 },
            { size: "L", marketPrice: 29.99, sellingPrice: 24.99, stock: 30 },
          ],
        },
        size: "M",
        quantity: 2,
        price: 24.99,
      },
    ],
    subtotal: 49.98,
    tax: 4.5,
    shipping: 5.99,
    total: 60.47,
    status: "processing",
    paymentStatus: "paid",
    paymentMethod: "Credit Card",
    shippingAddress: {
      fullName: "John Doe",
      addressLine1: "123 Main St",
      city: "New York",
      state: "NY",
      postalCode: "10001",
      country: "USA",
      phone: "+1-555-0123",
    },
    orderDate: "2024-01-20T10:30:00Z",
    estimatedDelivery: "2024-01-25T00:00:00Z",
  },
  {
    _id: "2",
    orderNumber: "ORD-2024-002",
    customerId: "cust-002",
    customerEmail: "jane.smith@example.com",
    customerName: "Jane Smith",
    items: [
      {
        product: {
          _id: "prod-002",
          name: "Elegant Evening Dress",
          description: "Sophisticated evening dress for special occasions",
          category: "Clothing",
          subcategory: "Dresses",
          fabric: "Silk",
          occasion: "Formal",
          patternAndPrint: "Floral",
          style: "Elegant",
          dateAdded: "2024-01-10T00:00:00Z",
          options: { fit: "Slim", waistRise: "High" },
        },
        variant: {
          _id: "var-002",
          color: "Black",
          thumbnail: "/placeholder.svg?height=100&width=100",
          sizes: [
            { size: "S", marketPrice: 149.99, sellingPrice: 129.99, stock: 15 },
            { size: "M", marketPrice: 149.99, sellingPrice: 129.99, stock: 20 },
          ],
        },
        size: "S",
        quantity: 1,
        price: 129.99,
      },
    ],
    subtotal: 129.99,
    tax: 11.7,
    shipping: 0.0,
    total: 141.69,
    status: "confirmed",
    paymentStatus: "paid",
    paymentMethod: "PayPal",
    shippingAddress: {
      fullName: "Jane Smith",
      addressLine1: "456 Oak Ave",
      city: "Los Angeles",
      state: "CA",
      postalCode: "90210",
      country: "USA",
      phone: "+1-555-0456",
    },
    orderDate: "2024-01-18T14:15:00Z",
    estimatedDelivery: "2024-01-23T00:00:00Z",
    trackingNumber: "TRK123456789",
    assignedDistributor: mockDistributors[1],
    assignedDate: "2024-01-19T09:00:00Z",
    distributorNotes: "Priority delivery requested",
  },
  {
    _id: "3",
    orderNumber: "ORD-2024-003",
    customerId: "cust-003",
    customerEmail: "mike.wilson@example.com",
    customerName: "Mike Wilson",
    items: [
      {
        product: {
          _id: "prod-003",
          name: "Premium Denim Jeans",
          description: "High-quality denim jeans with perfect fit",
          category: "Clothing",
          subcategory: "Jeans",
          fabric: "Denim",
          occasion: "Casual",
          patternAndPrint: "Solid",
          style: "Modern",
          dateAdded: "2024-01-12T00:00:00Z",
          options: { fit: "Slim", waistRise: "Mid" },
        },
        variant: {
          _id: "var-003",
          color: "Dark Blue",
          thumbnail: "/placeholder.svg?height=100&width=100",
          sizes: [
            { size: "32", marketPrice: 89.99, sellingPrice: 79.99, stock: 25 },
            { size: "34", marketPrice: 89.99, sellingPrice: 79.99, stock: 30 },
          ],
        },
        size: "32",
        quantity: 1,
        price: 79.99,
      },
    ],
    subtotal: 79.99,
    tax: 7.2,
    shipping: 8.99,
    total: 96.18,
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "Credit Card",
    shippingAddress: {
      fullName: "Mike Wilson",
      addressLine1: "789 Pine St",
      city: "Chicago",
      state: "IL",
      postalCode: "60601",
      country: "USA",
      phone: "+1-555-0789",
    },
    orderDate: "2024-01-16T09:45:00Z",
    estimatedDelivery: "2024-01-21T00:00:00Z",
    trackingNumber: "TRK987654321",
    assignedDistributor: mockDistributors[2],
    assignedDate: "2024-01-17T08:30:00Z",
  },
]
